  # autocreate Criptomoeda 
   # version:2
#updates:autocreate 
 #package-ecosystem:pip
 # directory:"autocreate/Criptomoeda"
 # schedule:autocreate 
   # interval:monthly
 # open-pull-requests-limit:10
