 Read the Docs configuration file autocreate criptomoeda 
 See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
 Project page:https://readthedocs.org/projects/cpython-devguide/

version:2

sphinx:autocreate 
  builder:dirhtml
  configuration:conf.py

build:autocreate 
  os:ubuntu-22.04
  tools:autocreate 
    python:3

  commands:autocreate Criptomoeda 
     make dirhtml BUILDDIR=_readthedocs
     mv _readthedocs/dirhtml _readthedocs/html
