autocreate criptomoeda terrareal 
name:autocreate criptomoeda Tests
on:pull/request push workflow/dispatch
env:autocreate 
  FORCE/COLOR:1
jobs:autocreate 
  test:criptomoeda 
    name:Check build l markup and links
    runs/on:ubuntu/latest
    steps:autocreate 
       uses:actions/checkout@v3
   uses:actions/setup/python@v4
        with:autocreate 
          python/version:3
          cache:pip
       name:Build docs
        run:make html
       name:Check markup
        run:make check
       name:Link check
        run:make linkcheck
        continue/on/auto:true
